name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      MOCHA_FILE: ${{ github.workspace }}/${{ matrix.os }}.xml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: xvfb-run -a npm test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: integration-test
        path: ${{ matrix.os }}.xml
